// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Build struct {
	ID            string      `json:"id"`
	ProjectID     string      `json:"projectID"`
	Project       *Project    `json:"project"`
	Number        int         `json:"number"`
	Status        BuildStatus `json:"status"`
	CommitHash    *string     `json:"commitHash,omitempty"`
	CommitMessage *string     `json:"commitMessage,omitempty"`
	StartedAt     *string     `json:"startedAt,omitempty"`
	FinishedAt    *string     `json:"finishedAt,omitempty"`
	Duration      *int        `json:"duration,omitempty"`
	CreatedAt     string      `json:"createdAt"`
	UpdatedAt     string      `json:"updatedAt"`
}

type BuildConnection struct {
	Edges      []*Build `json:"edges"`
	TotalCount int      `json:"totalCount"`
}

type CreateProjectInput struct {
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	RepositoryURL string  `json:"repositoryURL"`
	Branch        string  `json:"branch"`
}

type HealthStatus struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
	Version   string `json:"version"`
}

type LogLine struct {
	BuildID   string `json:"buildID"`
	Line      string `json:"line"`
	Timestamp string `json:"timestamp"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Node struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Hostname        string     `json:"hostname"`
	Architecture    string     `json:"architecture"`
	OperatingSystem string     `json:"operatingSystem"`
	Role            NodeRole   `json:"role"`
	Status          NodeStatus `json:"status"`
	Capacity        int        `json:"capacity"`
	CurrentLoad     int        `json:"currentLoad"`
	LastHeartbeat   *string    `json:"lastHeartbeat,omitempty"`
	CreatedAt       string     `json:"createdAt"`
	UpdatedAt       string     `json:"updatedAt"`
}

type NodeConnection struct {
	Edges      []*Node `json:"edges"`
	TotalCount int     `json:"totalCount"`
}

type Project struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description,omitempty"`
	RepositoryURL string           `json:"repositoryURL"`
	Branch        string           `json:"branch"`
	UserID        string           `json:"userID"`
	CreatedAt     string           `json:"createdAt"`
	UpdatedAt     string           `json:"updatedAt"`
	Builds        *BuildConnection `json:"builds"`
}

type ProjectConnection struct {
	Edges      []*Project `json:"edges"`
	TotalCount int        `json:"totalCount"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterNodeInput struct {
	Name            string   `json:"name"`
	Hostname        string   `json:"hostname"`
	Architecture    string   `json:"architecture"`
	OperatingSystem string   `json:"operatingSystem"`
	Role            NodeRole `json:"role"`
	Capacity        int      `json:"capacity"`
	Token           string   `json:"token"`
}

type Subscription struct {
}

type SystemMetrics struct {
	CPU          float64 `json:"cpu"`
	Memory       float64 `json:"memory"`
	Disk         float64 `json:"disk"`
	Goroutines   int     `json:"goroutines"`
	BuildQueue   int     `json:"buildQueue"`
	ActiveBuilds int     `json:"activeBuilds"`
}

type TriggerBuildInput struct {
	CommitHash *string `json:"commitHash,omitempty"`
	Branch     *string `json:"branch,omitempty"`
}

type UpdateNodeInput struct {
	Name     *string     `json:"name,omitempty"`
	Capacity *int        `json:"capacity,omitempty"`
	Status   *NodeStatus `json:"status,omitempty"`
}

type UpdateProjectInput struct {
	Name          *string `json:"name,omitempty"`
	Description   *string `json:"description,omitempty"`
	RepositoryURL *string `json:"repositoryURL,omitempty"`
	Branch        *string `json:"branch,omitempty"`
}

type UpdateUserInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	IsAdmin   bool   `json:"isAdmin"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserConnection struct {
	Edges      []*User `json:"edges"`
	TotalCount int     `json:"totalCount"`
}

type BuildStatus string

const (
	BuildStatusPending   BuildStatus = "PENDING"
	BuildStatusQueued    BuildStatus = "QUEUED"
	BuildStatusRunning   BuildStatus = "RUNNING"
	BuildStatusSuccess   BuildStatus = "SUCCESS"
	BuildStatusFailed    BuildStatus = "FAILED"
	BuildStatusCancelled BuildStatus = "CANCELLED"
)

var AllBuildStatus = []BuildStatus{
	BuildStatusPending,
	BuildStatusQueued,
	BuildStatusRunning,
	BuildStatusSuccess,
	BuildStatusFailed,
	BuildStatusCancelled,
}

func (e BuildStatus) IsValid() bool {
	switch e {
	case BuildStatusPending, BuildStatusQueued, BuildStatusRunning, BuildStatusSuccess, BuildStatusFailed, BuildStatusCancelled:
		return true
	}
	return false
}

func (e BuildStatus) String() string {
	return string(e)
}

func (e *BuildStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BuildStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BuildStatus", str)
	}
	return nil
}

func (e BuildStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BuildStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BuildStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeRole string

const (
	NodeRoleOrchestrator NodeRole = "ORCHESTRATOR"
	NodeRoleBuilder      NodeRole = "BUILDER"
	NodeRoleHybrid       NodeRole = "HYBRID"
)

var AllNodeRole = []NodeRole{
	NodeRoleOrchestrator,
	NodeRoleBuilder,
	NodeRoleHybrid,
}

func (e NodeRole) IsValid() bool {
	switch e {
	case NodeRoleOrchestrator, NodeRoleBuilder, NodeRoleHybrid:
		return true
	}
	return false
}

func (e NodeRole) String() string {
	return string(e)
}

func (e *NodeRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeRole", str)
	}
	return nil
}

func (e NodeRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeStatus string

const (
	NodeStatusOnline   NodeStatus = "ONLINE"
	NodeStatusOffline  NodeStatus = "OFFLINE"
	NodeStatusDraining NodeStatus = "DRAINING"
)

var AllNodeStatus = []NodeStatus{
	NodeStatusOnline,
	NodeStatusOffline,
	NodeStatusDraining,
}

func (e NodeStatus) IsValid() bool {
	switch e {
	case NodeStatusOnline, NodeStatusOffline, NodeStatusDraining:
		return true
	}
	return false
}

func (e NodeStatus) String() string {
	return string(e)
}

func (e *NodeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeStatus", str)
	}
	return nil
}

func (e NodeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
